apiVersion: apps/v1
kind: Deployment
metadata: { name: pricing-service-deployment }
spec:
  replicas: 2
  selector: { matchLabels: { app: pricing-service } }
  template:
    metadata: { labels: { app: pricing-service } }
    spec:
      containers:
        - name: pricing-service-container
          image: pricing-service:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 3003 }]
          env:
            - name: PORT
              value: "3003"
          readinessProbe:
            httpGet: { path: /health, port: 3003 }
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata: { name: pricing-svc }
spec:
  selector: { app: pricing-service }
  ports: [{ name: http, port: 80, targetPort: 3003 }]
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: inventory-service-deployment }
spec:
  replicas: 2
  selector: { matchLabels: { app: inventory-service } }
  template:
    metadata: { labels: { app: inventory-service } }
    spec:
      containers:
        - name: inventory-service-container
          image: inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 3002 }]
          env:
            - name: PORT
              value: "3002"
          readinessProbe:
            httpGet: { path: /health, port: 3002 }
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata: { name: inventory-svc }
spec:
  selector: { app: inventory-service }
  ports: [{ name: http, port: 80, targetPort: 3002 }]
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: checkout-service-deployment }
spec:
  replicas: 2
  selector: { matchLabels: { app: checkout-service } }
  template:
    metadata: { labels: { app: checkout-service } }
    spec:
      containers:
        - name: checkout-service-container
          image: checkout-service:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 3001 }]
          env:
            - name: PRICING_URL
              value: http://pricing-svc
            - name: INVENTORY_URL
              value: http://inventory-svc
            - name: TIMEOUT_MS
              value: "1500"
            - name: PORT
              value: "3001"
          readinessProbe:
            httpGet: { path: /health, port: 3001 }
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata: { name: checkout-svc }
spec:
  selector: { app: checkout-service }
  ports: [{ name: http, port: 80, targetPort: 3001 }]
